sonar.projectKey=dhruvchaubey28_technova-project
sonar.organization=dhruvchaubey28

# Project Information
sonar.projectName=TechNova Application
sonar.projectVersion=1.0

# Source code location
sonar.sources=.
sonar.tests=tests

# Exclusions
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/venv/**,**/.terraform/**,**/build/**,**/dist/**

# Language specific settings
sonar.python.coverage.reportPaths=coverage.xml

# For JavaScript/TypeScript (if applicable)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
